### ISSUE TITLE
TexLive installation failing on Travis-CI

### ISSUE THREAD

**Issue by mrustl** [yihui/ubuntu-bin#1]
Do you have any idea why I receive the following error message on the Travis-CI since today?

`$ curl -Lo /tmp/texlive.tar.gz https://github.com/yihui/ubuntu-bin/releases/download/latest/texlive.tar.gz`

 `$ tar xzf /tmp/texlive.tar.gz -C ~`

`$ export PATH=/$HOME/texlive/bin/x86_64-linux:$PATH`

`$ tlmgr update --self`

`Unknown directive ...containerchecksum c59200574a316416a23695c258edf3a32531fbda43ccdc09360ee105c3f07f9fb77df17c4ba4c2ea4f3a5ea6667e064b51e3d8c2fe6c984ba3e71b4e32716955... , please fix it! at /home/travis/texlive/tlpkg/TeXLive/TLPOBJ.pm line 210, <$retfh> line 5579.`

Complete log: https://travis-ci.org/KWB-R/kwb.utils

**Comment by yihui** [comment]
Thanks for the report. @jimhester has fixed the issue, and you just need to trigger the travis build again.
