### ISSUE TITLE
404 after switching from .name to .org?

### ISSUE THREAD

**Issue by zeehio** [yihui/ubuntu-bin#2]
Hi Yihui,

Sorry to bother you if this is a temporary issue, I don't know for how long it has been like this.

Apparently [https://travis-bin.yihui.name/texlive-local.deb](https://travis-bin.yihui.name/texlive-local.deb) redirects to [https://travis-bin.yihui.org/texlive-local.deb](https://travis-bin.yihui.org/texlive-local.deb) that leads to a 404, not found.

This deb file is used in the rocker/verse docker image, that is failing to build. See the wget call [here](https://github.com/rocker-org/rocker-versioned/blob/0842c3b58e6e5ed8aac2f8e15705f68f3c6fc50b/verse/Dockerfile#L13)

Can the 404 be fixed, or should the link be replaced? (or both?)

**Comment by yihui** [comment]
Your PR #3 is spot on. I did the 301 redirect but forgot that Travis still (over)writes travis-bin.yihui.name in CNAME. Now everything should work fine. Thanks again!
