### ISSUE TITLE
Issue while building new pandoc 2.11

### ISSUE THREAD

**Issue by cderv** [yihui/ubuntu-bin#4]
I was not sure why rmarkdown was not currently tested with the last devel version of pandoc:  2.11
https://travis-ci.org/github/rstudio/rmarkdown/jobs/735205503#L851

but now that I have looked into the chain, this is because your process here does not build new version of Pandoc
https://travis-ci.com/github/yihui/travis-bin/builds/189518088#L343

I guess the process have changed

If we plan to still use this daily build, this should be fixed in order to have Rmarkdown and others tested with Pandoc 2.11

I can help if you want - just tell me.

**Comment by cderv** [comment]
And it may not be necessary anymore to use this daily build because pandoc repo if now offering one. 

They use Github Actions and they publish a nightly build: https://github.com/jgm/pandoc/actions/runs/303922548

The workflow file is here: https://github.com/jgm/pandoc/blob/master/.github/workflows/nightly.yml

We could use that instead. What do you think ?

**Comment by cderv** [comment]
One challenge is that the url is not fixed but we could get the last nightly artifacts using 
```sh
  curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/jgm/pandoc/actions/artifacts | jq '.artifacts | map(select(.name == "nightly-linux")) | .[1].archive_download_url'
```

[jq](https://stedolan.github.io/jq) is really helpful here and easy to install on Linux. 

This would get us the url of the last nightly build for linux
```sh
curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/jgm/pandoc/actions/artifacts | jq '.artifacts| map(select(.name == "nightly-linux")) | .[0].archive_download_url'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14853  100 14853    0     0   7632      0  0:00:01  0:00:01 --:--:--  7628
"https://api.github.com/repos/jgm/pandoc/actions/artifacts/21334351/zip"
```

We could then download the file from the api. we may need a GH token with the correct scope. 

I'll try to do that this afternoon in travis for rmarkdown.

**Comment by yihui** [comment]
I noticed that last week, too, and meant to look into it but haven't got a chance. Thanks for the investigation and tips! They were super helpful. I'll probably just download Pandoc's daily build to this repo, and re-publish it so we can have a stable link.

**Comment by cderv** [comment]
Oh ok. That means your travis cron should be synchronize with the Pandoc GHA one so that we don't have any delay ! 

I was planning to add that in rmarkdown repo
```sh
sudo apt install jq
latest_url=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/jgm/pandoc/actions/artifacts | jq -r '.artifacts| map(select(.name == "nightly-linux")) | .[0].archive_download_url')
curl -L -o pandoc.zip -u :$GITHUB_TOKEN $latest_url
unzip -j -d . pandoc.zip
```
But I could add it here instead.

**Comment by yihui** [comment]
Okay. Let me try that after the meeting. Thanks!

**Comment by cderv** [comment]
Cool ! 
There may be a scope issue with token, but not sure. It worked with mine locally but I don't remember which scope I have. 

Version with github cli command: 
```sh
latest_url=gh api /repos/jgm/pandoc/actions/artifacts | jq -r '.artifacts| map(select(.name == "nightly-linux")) | .[0].archive_download_url'
gh api $latest_url > pandoc.zip
```
For it to work you would need to install the cli tool and also have GITHUB_TOKEN environment variable setup. 

Just sharing in case you find that clearer.

**Comment by cderv** [comment]
Oh and I believe the artifacts are sorted in the correct order in the API response, but it case we want to be sure we can also sort the response using this js command

```sh
jq -r '.artifacts| map(select(.name == "nightly-linux")) | map({ url: .archive_download_url, when: .updated_at | fromdateiso8601 }) | sort_by(.when) | last.url'
```

**Comment by yihui** [comment]
Great. I just pushed the code and will see how the build goes. Thanks again!

**Comment by yihui** [comment]
Seems to be working now: https://travis-ci.org/github/rstudio/rmarkdown/jobs/735447123#L837

**Comment by cderv** [comment]
Awesome !
